openapi: 3.0.0
info:
  title: Entertainment Web
  description: Entertainment web API
  version: 0.1.9

servers:
  - url: https://folksoul-api-nikanoza-production.up.railway.app/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /user/films:
    post:
      tags:
        - film
      requestBody:
        description: add film
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                title:
                  type: string
                year:
                  type: number
                category:
                  type: string
                rating:
                  type: string
                isBookmarked:
                  type: boolean
                isTrending:
                  type: boolean
      responses:
        "200":
          description: film add
