openapi: 3.0.0
info:
  title: Entertainment Web
  description: Entertainment web API
  version: 0.1.9

servers:
  - url: https://entertainment-web.onrender.com/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /films:
    post:
      tags:
        - films
      requestBody:
        description: add film
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                title:
                  type: string
                year:
                  type: number
                category:
                  type: string
                rating:
                  type: string
                isBookmarked:
                  type: boolean
                isTrending:
                  type: boolean
      responses:
        "200":
          description: film add
  /user/signup:
    post:
      tags:
        - user
      requestBody:
        description: add user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: user add
  /user/login:
    post:
      tags:
        - user
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /film:
    get:
      tags:
        - Film
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                 avatar:
                  type: string
                  format: binary
                title:
                  type: string
                year:
                  type: number
                category:
                  type: string
                rating:
                  type: string
                isBookmarked:
                  type: boolean
                isTrending:
                  type: boolean
  /users:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                avatar:
                  type: string
                  format: binary
                email:
                  type: string
                password:
                  type: string